### ISSUE TITLE
Error when building with fpm

### ISSUE THREAD

**Issue by general-rishkin** [urbanjost/M_strings#4]
I just included M_strings as a dependency in my project. On doing `fpm run`, I get the following error in M_strings. This is wwith gfortran version 8.3.0 .

```
build/dependencies/M_strings/src/M_strings.F90:8854:35:

 real,parameter    :: XMAXREAL=real(huge(1))
                                   1
Warning: Change of value in conversion from ‘INTEGER(4)’ to ‘REAL(4)’ at (1) [-Wconversion]
build/dependencies/M_strings/src/M_strings.F90:6711:50:

 integer                      :: matrix(0:len_trim(a), 0:len_trim(b))
                                                  1
Error: Dummy argument ‘a’ not allowed in expression at (1)
compilation terminated due to -fmax-errors=1.
```

**Comment by urbanjost** [comment]
That old version of the compiler did not support that more modern declaration. I do not have a version that old to test with, but if that is the only error I will change the code to use older syntax. That is in a relatively obscure function and should have no performance issue anyway.

If using fpm(1) it does not get dependencies that change automatically;so if you flush the dependency cache with "fpm clean --all"   or run "fpm update"  it should get the new version; which
should have that problem resolved by creating an allocatable array and allocating it instead.

**Comment by general-rishkin** [comment]
Excellent, thanks
