### ISSUE TITLE
fpm test error

### ISSUE THREAD

**Issue by Syize** [urbanjost/M_strings#5]
Here is the log:

```
<ERROR>*cmd_run*:package error:Key fortran is not allowed in package file
STOP 1
```

OS: Arch Linux
Fortran compiler: gfortran 12.2.1

**Comment by urbanjost** [comment]
The fpm.toml file required fpm 0.8.0 or higher.  I was updating/testing everything to the latest fpm version to make my projects acceptable for use with the soon-to-be-available (hopefully) fpm repository.   I guess it is to early and it will be a while before that version will be common. Along with it not being a backward-compatible release I commented out the new directives so it should work again with pre-0.8.0 fpm commands. 

Thanks!  Give it a try now ...
